# Generated by Django 5.0.3 on 2024-03-21 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('is_active', models.BooleanField(default=True)),
                ('district_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.district')),
            ],
        ),
    ]
