# Generated by Django 5.0.3 on 2024-03-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_packagedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetail',
            name='place_description',
            field=models.CharField(max_length=255),
        ),
    ]
