# Generated by Django 5.0.3 on 2024-04-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_booking_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cart_book',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='travelapp.carts'),
            preserve_default=False,
        ),
    ]
