# Generated by Django 5.0.3 on 2024-04-04 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_booking_cart_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cart_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelapp.carts'),
        ),
    ]
