# Generated by Django 5.0.3 on 2024-04-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_alter_booking_cart_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='package_name',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Carts',
        ),
    ]
